$dest = 'C:\Users\Bilel\Documents\brawlhallasite\public\legends'

$images = @{
    'bodvar' = 'https://cms.brawlhalla.com/c/uploads/2021/07/bodvar.png'
    'cassidy' = 'https://cms.brawlhalla.com/c/uploads/2021/07/cassidy.png'
    'orion' = 'https://cms.brawlhalla.com/c/uploads/2021/07/orion.png'
    'vraxx' = 'https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_VraxxM-1.png'
    'gnash' = 'https://cms.brawlhalla.com/c/uploads/2021/07/gnash.png'
    'nai' = 'https://cms.brawlhalla.com/c/uploads/2021/07/nai.png'
    'hattori' = 'https://cms.brawlhalla.com/c/uploads/2021/07/hattori.png'
    'roland' = 'https://cms.brawlhalla.com/c/uploads/2021/07/roland.png'
    'scarlet' = 'https://cms.brawlhalla.com/c/uploads/2021/07/scarlet.png'
    'thatch' = 'https://cms.brawlhalla.com/c/uploads/2021/07/thatch.png'
    'ada' = 'https://cms.brawlhalla.com/c/uploads/2021/07/ada.png'
    'sentinel' = 'https://cms.brawlhalla.com/c/uploads/2021/07/sentinel.png'
    'lucien' = 'https://cms.brawlhalla.com/c/uploads/2021/07/lucien.png'
    'teros' = 'https://cms.brawlhalla.com/c/uploads/2021/07/teros.png'
    'brynn' = 'https://cms.brawlhalla.com/c/uploads/2021/07/brynn.png'
    'asuri' = 'https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_AsuriM.png'
    'barraza' = 'https://cms.brawlhalla.com/c/uploads/2021/07/barraza.png'
    'ember' = 'https://cms.brawlhalla.com/c/uploads/2021/07/ember.png'
    'azoth' = 'https://cms.brawlhalla.com/c/uploads/2021/07/azoth.png'
    'koji' = 'https://cms.brawlhalla.com/c/uploads/2021/07/koji.png'
    'ulgrim' = 'https://cms.brawlhalla.com/c/uploads/2021/07/ulgrim.png'
    'diana' = 'https://cms.brawlhalla.com/c/uploads/2021/07/diana.png'
    'jhala' = 'https://cms.brawlhalla.com/c/uploads/2021/07/jhala.png'
    'kor' = 'https://cms.brawlhalla.com/c/uploads/2021/07/kor.png'
    'wushang' = 'https://cms.brawlhalla.com/c/uploads/2021/07/wushang.png'
    'val' = 'https://cms.brawlhalla.com/c/uploads/2021/07/val.png'
    'ragnir' = 'https://cms.brawlhalla.com/c/uploads/2021/07/ragnir.png'
    'cross' = 'https://cms.brawlhalla.com/c/uploads/2021/07/cross.png'
    'mirage' = 'https://cms.brawlhalla.com/c/uploads/2021/07/mirage.png'
    'nix' = 'https://cms.brawlhalla.com/c/uploads/2021/07/nix.png'
    'mordex' = 'https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_MordexM.png'
    'yumiko' = 'https://cms.brawlhalla.com/c/uploads/2021/07/yumiko.png'
    'artemis' = 'https://cms.brawlhalla.com/c/uploads/2021/07/artemis.png'
    'caspian' = 'https://cms.brawlhalla.com/c/uploads/2021/07/caspian.png'
    'sidra' = 'https://cms.brawlhalla.com/c/uploads/2021/07/sidra.png'
    'xull' = 'https://cms.brawlhalla.com/c/uploads/2021/07/xull.png'
    'kaya' = 'https://cms.brawlhalla.com/c/uploads/2021/07/kaya.png'
    'isaiah' = 'https://cms.brawlhalla.com/c/uploads/2021/07/isaiah.png'
    'jiro' = 'https://cms.brawlhalla.com/c/uploads/2021/07/jiro.png'
    'linfei' = 'https://cms.brawlhalla.com/c/uploads/2021/07/linfei.png'
    'zariel' = 'https://cms.brawlhalla.com/c/uploads/2021/07/zariel.png'
    'rayman' = 'https://cms.brawlhalla.com/c/uploads/2021/07/rayman.png'
    'dusk' = 'https://cms.brawlhalla.com/c/uploads/2021/07/dusk.png'
    'fait' = 'https://cms.brawlhalla.com/c/uploads/2021/07/fait.png'
    'thor' = 'https://cms.brawlhalla.com/c/uploads/2021/07/a_Roster_Pose_ThorM.png'
    'petra' = 'https://cms.brawlhalla.com/c/uploads/2021/07/petra.png'
    'vector' = 'https://cms.brawlhalla.com/c/uploads/2021/07/vector.png'
    'volkov' = 'https://cms.brawlhalla.com/c/uploads/2021/07/volkov.png'
    'onyx' = 'https://cms.brawlhalla.com/c/uploads/2021/07/onyx.png'
    'jaeyun' = 'https://cms.brawlhalla.com/c/uploads/2021/07/jaeyun.png'
    'mako' = 'https://cms.brawlhalla.com/c/uploads/2021/07/mako.png'
    'magyar' = 'https://cms.brawlhalla.com/c/uploads/2021/07/magyar.png'
    'reno' = 'https://cms.brawlhalla.com/c/uploads/2021/10/a_Roster_Pose_BountyHunterM.png'
    'munin' = 'https://cms.brawlhalla.com/c/uploads/2021/12/a_Roster_Pose_BirdBardM.png'
    'arcadia' = 'https://cms.brawlhalla.com/c/uploads/2022/03/a_Roster_Pose_FairyQueenM.png'
    'ezio' = 'https://cms.brawlhalla.com/c/uploads/2022/06/a_Roster_Pose_EzioM.png'
    'tezca' = 'https://cms.brawlhalla.com/c/uploads/2022/12/a_Roster_Pose_LuchadorM.png'
    'thea' = 'https://cms.brawlhalla.com/c/uploads/2022/09/a_Roster_Pose_SpeedsterM.png'
    'redraptor' = 'https://cms.brawlhalla.com/c/uploads/2023/03/a_Roster_Pose_RedRaptorM.png'
    'loki' = 'https://cms.brawlhalla.com/c/uploads/2023/06/a_Roster_Pose_LokiM.png'
    'seven' = 'https://cms.brawlhalla.com/c/uploads/2023/09/a_Roster_Pose_SevenM.png'
    'vivi' = 'https://cms.brawlhalla.com/c/uploads/2023/12/a_Roster_Pose_ViviM.png'
    'nimue' = 'https://cms.brawlhalla.com/c/uploads/2024/03/a_Roster_Pose_NimueM.png'
}

foreach ($k in $images.Keys) {
    $out = Join-Path $dest "$k.png"
    try {
        Invoke-WebRequest -Uri $images[$k] -OutFile $out -ErrorAction Stop
        Write-Host "$k OK"
    } catch {
        Write-Host "$k FAIL - $($_.Exception.Message)"
    }
}
